// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['services']['App']['CloseWindow']();
}

export function GetAgentProcessStatus() {
  return window['go']['services']['App']['GetAgentProcessStatus']();
}

export function GetClawConnectionConfig() {
  return window['go']['services']['App']['GetClawConnectionConfig']();
}

export function Greet(arg1) {
  return window['go']['services']['App']['Greet'](arg1);
}

export function MinimizeWindow() {
  return window['go']['services']['App']['MinimizeWindow']();
}

export function RestartAgent() {
  return window['go']['services']['App']['RestartAgent']();
}

export function SetClawConnectionConfig(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['services']['App']['SetClawConnectionConfig'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StopAgent() {
  return window['go']['services']['App']['StopAgent']();
}

export function WakeAgent() {
  return window['go']['services']['App']['WakeAgent']();
}
