// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function CloseWindow():Promise<void>;

export function GetAgentProcessStatus():Promise<services.AgentProcessStatus>;

export function GetClawConnectionConfig():Promise<Record<string, string>>;

export function Greet(arg1:string):Promise<string>;

export function MinimizeWindow():Promise<void>;

export function RestartAgent():Promise<services.AgentProcessStatus>;

export function SetClawConnectionConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function StopAgent():Promise<services.AgentProcessStatus>;

export function WakeAgent():Promise<services.AgentProcessStatus>;
